// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v3.19.6
// source: api/proto/ai.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiRequest) Reset() {
	*x = AiRequest{}
	mi := &file_api_proto_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiRequest) ProtoMessage() {}

func (x *AiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiRequest.ProtoReflect.Descriptor instead.
func (*AiRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_ai_proto_rawDescGZIP(), []int{0}
}

func (x *AiRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type AiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AiResponse) Reset() {
	*x = AiResponse{}
	mi := &file_api_proto_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiResponse) ProtoMessage() {}

func (x *AiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiResponse.ProtoReflect.Descriptor instead.
func (*AiResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_ai_proto_rawDescGZIP(), []int{1}
}

func (x *AiResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

var File_api_proto_ai_proto protoreflect.FileDescriptor

var file_api_proto_ai_proto_rawDesc = string([]byte{
	0x0a, 0x12, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x69, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x27, 0x0a, 0x09, 0x41, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x24, 0x0a, 0x0a, 0x41,
	0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x32, 0x47, 0x0a, 0x09, 0x41, 0x69, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a,
	0x0a, 0x03, 0x41, 0x73, 0x6b, 0x12, 0x17, 0x2e, 0x61, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18,
	0x2e, 0x61, 0x69, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x69,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_api_proto_ai_proto_rawDescOnce sync.Once
	file_api_proto_ai_proto_rawDescData []byte
)

func file_api_proto_ai_proto_rawDescGZIP() []byte {
	file_api_proto_ai_proto_rawDescOnce.Do(func() {
		file_api_proto_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_ai_proto_rawDesc), len(file_api_proto_ai_proto_rawDesc)))
	})
	return file_api_proto_ai_proto_rawDescData
}

var file_api_proto_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_ai_proto_goTypes = []any{
	(*AiRequest)(nil),  // 0: ai.api.proto.AiRequest
	(*AiResponse)(nil), // 1: ai.api.proto.AiResponse
}
var file_api_proto_ai_proto_depIdxs = []int32{
	0, // 0: ai.api.proto.AiService.Ask:input_type -> ai.api.proto.AiRequest
	1, // 1: ai.api.proto.AiService.Ask:output_type -> ai.api.proto.AiResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_ai_proto_init() }
func file_api_proto_ai_proto_init() {
	if File_api_proto_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_ai_proto_rawDesc), len(file_api_proto_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_ai_proto_goTypes,
		DependencyIndexes: file_api_proto_ai_proto_depIdxs,
		MessageInfos:      file_api_proto_ai_proto_msgTypes,
	}.Build()
	File_api_proto_ai_proto = out.File
	file_api_proto_ai_proto_goTypes = nil
	file_api_proto_ai_proto_depIdxs = nil
}
